services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tm_sdk_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5438:5432'
    volumes:
      - ./data/sql/initTestDb.sql:/docker-entrypoint-initdb.d/initTestDb.sql
